# application.yml 主配置文件
spring:
  #  配置激活文件
  profiles:
    active: dev
    # 对配置文件进行分组激活，届时可根据不同环境进行修改
    group:
      "dev": project,datasource,redis,rabbitmq,mail,scheduled,private
      "prod": project,datasource,redis,rabbitmq,mail,scheduled,private
      "test": project,datasource,redis,rabbitmq,mail,scheduled,private
  # 限制文件大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

